'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
function memoryStorage(){const data=new Map();return{getItem:k=>data.has(k)?data.get(k):null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)}}
global.localStorage=memoryStorage();
delete global.RollandsDemoScenario;delete global.RollandsDemoWorkflows;
require('../apps/portal/demo-scenario.js');
require('../apps/portal/demo-workflows.js');
const Demo=global.RollandsDemoScenario,Flows=global.RollandsDemoWorkflows;
function balanced(entry){const debit=entry.lines.reduce((s,l)=>s+Number(l.debitOre||0),0),credit=entry.lines.reduce((s,l)=>s+Number(l.creditOre||0),0);return debit===credit}

test('gemensamt demoscenario laddas och kan återställas',()=>{assert.ok(Demo);const state=Demo.state();assert.equal(state.version,Demo.VERSION);assert.ok(state.customers.length>=4);assert.ok(state.inventoryItems.length>=3);assert.ok(state.payrollRuns.length>=1);Demo.patch(next=>{next.bankPayments[0].status='proposal-created'});assert.equal(Demo.state().bankPayments[0].status,'proposal-created');assert.equal(Demo.reset().bankPayments[0].status,'unmatched')});

test('kundregister, kundfaktura och bokföring använder samma affärsobjekt',()=>{Demo.reset();const customer=Flows.createCustomer({name:'Demo Kund AB',orgNumber:'559999-9999',email:'ekonomi@demokund.example',paymentTermsDays:30,reminderFeeAgreed:true});const invoice=Flows.createCustomerInvoice({customerId:customer.id,invoiceDate:Demo.AS_OF_DATE,dueDate:'2026-10-17',description:'Företagsfrukt',quantityMilli:2000,unitPriceOre:100000,vatBasisPoints:2500});assert.equal(invoice.totalOre,250000);assert.equal(invoice.status,'Utkast');let state=Flows.postCustomerInvoice(invoice.id);const posted=state.customerInvoices.find(i=>i.id===invoice.id),entry=state.accountingEntries.find(e=>e.sourceType==='customer-invoice'&&e.sourceId===invoice.id);assert.equal(posted.status,'Bokförd');assert.equal(posted.remainingOre,250000);assert.ok(entry);assert.ok(balanced(entry));assert.deepEqual(entry.lines.map(l=>l.account),['1510','3010','2611'])});

test('bankmatchning 310002 använder samma restbelopp och faktura i alla lager',()=>{const state=Demo.reset(),payment=state.bankPayments.find(row=>row.reference==='310002'),invoice=state.customerInvoices.find(row=>row.invoiceNumber==='310002'),proposal=state.automationProposals.find(row=>row.type==='bank-payment-match'&&row.suggestion.invoiceNumber==='310002');assert.ok(payment&&invoice&&proposal);assert.equal(payment.amountOre,392500);assert.equal(invoice.remainingOre,payment.amountOre);assert.equal(proposal.review.amountOre,payment.amountOre);assert.equal(proposal.suggestion.invoiceId,invoice.id);assert.deepEqual(proposal.review.accountingLines.map(row=>[row.account,row.debitOre,row.creditOre]),[['1930',392500,0],['1510',0,392500]])});

test('godkänd kundinbetalning nollar reskontran och skapar balanserad bokföring',()=>{Demo.reset();const state=Flows.applyCustomerPayment('bank-demo-2'),invoice=state.customerInvoices.find(i=>i.invoiceNumber==='310002'),payment=state.bankPayments.find(p=>p.id==='bank-demo-2'),entry=state.accountingEntries.find(e=>e.sourceType==='bank-payment'&&e.sourceId==='bank-demo-2');assert.equal(invoice.status,'Betald');assert.equal(invoice.remainingOre,0);assert.equal(payment.status,'posted');assert.ok(entry);assert.ok(balanced(entry));assert.deepEqual(entry.lines.map(l=>l.account),['1930','1510'])});

test('automationsförslag för leverantörsfaktura pekar på verklig demofaktura och leverantör',()=>{const state=Demo.reset(),proposal=state.automationProposals.find(row=>row.type==='supplier-invoice-coding'),invoice=state.supplierInvoices.find(row=>row.id===proposal.sourceId),supplier=state.suppliers.find(row=>row.id===invoice.supplierId);assert.equal(invoice.supplierInvoiceNumber,'KE-2088');assert.equal(supplier.name,'Kustens Emballage AB');assert.equal(proposal.context.supplierName,supplier.name);assert.equal(proposal.review.amountOre,invoice.totalOre)});

test('dokumentkopplingar till leverantörsfaktura pekar på befintliga fakturor',()=>{const state=Demo.reset(),ids=new Set(state.supplierInvoices.map(row=>row.id)),links=state.documents.flatMap(document=>(document.links||[]).filter(link=>link.entityType==='supplier-invoice'));assert.ok(links.length>=2);for(const link of links)assert.ok(ids.has(link.entityId),`Saknad leverantörsfaktura för dokumentlänk ${link.entityId}`)});

test('bokförd leverantörsbetalning GF-8821 har motsvarande betalning och balanserad verifikation',()=>{const state=Demo.reset(),payment=state.supplierPayments.find(row=>row.supplierInvoiceNumber==='GF-8821'),entry=state.accountingEntries.find(row=>row.sourceId===payment.id);assert.ok(entry);assert.ok(balanced(entry));assert.equal(entry.lines.reduce((sum,row)=>sum+row.debitOre,0),payment.amountOre);assert.deepEqual(entry.lines.map(row=>row.account),['2440','1930'])});

test('BKS-771 bokför skuld, förbereds, frisläpps, bankbekräftas och nollar 2440',()=>{Demo.reset();let state=Flows.postSupplierInvoice('sinv-demo-3');let invoice=state.supplierInvoices.find(row=>row.id==='sinv-demo-3');const invoiceEntry=state.accountingEntries.find(row=>row.sourceType==='supplier-invoice'&&row.sourceId==='sinv-demo-3');assert.ok(invoiceEntry);assert.equal(invoice.openAmountOre,437500);state=Flows.prepareSupplierPayment('sinv-demo-3');invoice=state.supplierInvoices.find(row=>row.id==='sinv-demo-3');let payment=state.supplierPayments.find(row=>row.supplierInvoiceId==='sinv-demo-3');assert.equal(invoice.status,'payment-prepared');assert.equal(payment.status,'prepared');state=Flows.releaseSupplierPayment(payment.id);payment=state.supplierPayments.find(row=>row.id===payment.id);assert.equal(payment.status,'released');state=Flows.confirmSupplierPayment(payment.id,'BANK-DEMO-BKS-771');invoice=state.supplierInvoices.find(row=>row.id==='sinv-demo-3');payment=state.supplierPayments.find(row=>row.id===payment.id);const paymentEntry=state.accountingEntries.find(row=>row.sourceType==='supplier-payment'&&row.sourceId===payment.id);assert.equal(invoice.status,'paid');assert.equal(invoice.openAmountOre,0);assert.equal(payment.status,'paid');assert.ok(paymentEntry);assert.ok(balanced(paymentEntry));const net2440=[invoiceEntry,paymentEntry].flatMap(entry=>entry.lines).filter(row=>row.account==='2440').reduce((sum,row)=>sum+row.debitOre-row.creditOre,0);assert.equal(net2440,0)});

test('betalningsflödet stoppar förberedelse före skuldbokföring och bankbekräftelse utan frisläppning',()=>{Demo.reset();assert.throws(()=>Flows.releaseSupplierPayment('saknas'),error=>error.code==='DEMO_PAYMENT_NOT_FOUND');assert.throws(()=>Flows.prepareSupplierPayment('sinv-demo-3'),error=>error.code==='DEMO_LIABILITY_NOT_POSTED');Flows.postSupplierInvoice('sinv-demo-3');Flows.prepareSupplierPayment('sinv-demo-3');const payment=Demo.state().supplierPayments.find(row=>row.supplierInvoiceId==='sinv-demo-3');assert.throws(()=>Flows.confirmSupplierPayment(payment.id),error=>error.code==='DEMO_PAYMENT_NOT_RELEASED')});

test('lager, lön och alla initiala verifikationer är sammanhängande',()=>{const state=Demo.reset();for(const adjustment of state.inventoryAdjustments)assert.ok(state.inventoryItems.some(i=>i.id===adjustment.itemId));for(const run of state.payrollRuns)assert.equal(run.lines.reduce((s,l)=>s+l.debitOre,0),run.lines.reduce((s,l)=>s+l.creditOre,0));for(const entry of state.accountingEntries)assert.ok(balanced(entry),`${entry.number} balanserar inte`)});
