const app=document.getElementById('customers-app');
const Demo=globalThis.RollandsDemoScenario,Flows=globalThis.RollandsDemoWorkflows;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let customers=[],query='',message='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function q(path){if(!isDemo)return path;return `${path}${path.includes('?')?'&':'?'}demo=1`}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB<br>Demoföretag</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${q('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link active" href="${q('./customers.html')}">Kunder</a><a class="side-link" href="${q('./invoices.html')}">Kundfakturor</a><a class="side-link" href="${q('./receivables.html')}">Kundreskontra</a></div><div class="sidebar-footer">Fiktiva kunder i gemensamt demoscenario.</div></aside>`}
function visible(){const n=query.trim().toLowerCase();return customers.filter(c=>!n||[c.customerNumber,c.name,c.orgNumber,c.email,c.phone].some(v=>String(v||'').toLowerCase().includes(n)))}
function render(){const rows=visible();app.innerHTML=`<div class="sales-shell">${sidebar()}<section class="sales-main"><header class="topbar"><div><h1>Kunder</h1><p>Försäljning · kundregister</p></div><div class="user-chip"><b>Demo Försäljning</b></div></header><main class="sales-content"><div class="demo-banner"><b>Gemensam demo.</b> Kunder som skapas här kan direkt användas när en kundfaktura skapas.</div>${message?`<div class="notice">${esc(message)}</div>`:''}<section class="sales-summary"><article><span>Aktiva kunder</span><strong>${customers.filter(c=>c.active).length}</strong></article><article><span>30 dagars villkor</span><strong>${customers.filter(c=>c.paymentTermsDays===30).length}</strong></article><article><span>Påminnelseavgift avtalad</span><strong>${customers.filter(c=>c.reminderFeeAgreed).length}</strong></article><article><span>Företagskunder</span><strong>${customers.filter(c=>c.customerType==='business').length}</strong></article></section><div class="sales-toolbar"><input type="search" data-search value="${esc(query)}" placeholder="Sök kund, org.nr eller e-post"><button class="button" data-action="new">Ny kund</button></div><section class="sales-panel"><div class="sales-head"><div><span class="eyebrow">Kundregister</span><h2>${rows.length} kunder</h2></div><a class="button ghost" href="${q('./invoices.html')}">Gå till kundfakturor</a></div><div class="sales-table-wrap"><table class="sales-table"><thead><tr><th>Kundnr</th><th>Namn</th><th>Org.nr</th><th>Kontakt</th><th>Villkor</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><b>${esc(c.customerNumber)}</b></td><td>${esc(c.name)}</td><td>${esc(c.orgNumber||'—')}</td><td>${esc(c.email)}<br><small>${esc(c.phone||'')}</small></td><td>${esc(c.paymentTermsDays)} dagar</td><td><a class="button ghost small" href="${q(`./invoices.html?customer=${encodeURIComponent(c.id)}`)}">Skapa faktura</a></td></tr>`).join('')||'<tr><td colspan="6" class="empty-note">Inga kunder matchar sökningen.</td></tr>'}</tbody></table></div></section></main></section></div>`}
function modal(){document.body.insertAdjacentHTML('beforeend',`<div class="sales-modal-backdrop" data-close><section class="sales-modal" data-stop><header><div><span class="eyebrow">Ny kund</span><h2>Lägg till kund</h2></div><button type="button" data-close>×</button></header><form class="sales-form" id="customer-form"><div class="two"><label>Företagsnamn<input name="name" required></label><label>Organisationsnummer<input name="orgNumber"></label></div><div class="two"><label>E-post<input name="email" type="email" required></label><label>Telefon<input name="phone"></label></div><div class="two"><label>Betalningsvillkor<select name="paymentTermsDays"><option value="10">10 dagar</option><option value="20">20 dagar</option><option value="30" selected>30 dagar</option></select></label><label><span>Påminnelseavgift</span><select name="reminderFeeAgreed"><option value="yes">Avtalad</option><option value="no">Inte avtalad</option></select></label></div><div class="sales-actions"><button type="button" class="button ghost" data-close>Avbryt</button><button class="button" type="submit">Spara kund</button></div></form></section></div>`)}
document.addEventListener('input',e=>{if(e.target.matches('[data-search]')){query=e.target.value;render()}});
document.addEventListener('click',e=>{if(e.target.closest('[data-action="new"]'))modal();if((e.target.matches('[data-close]')||e.target.closest('[data-close]'))&&!e.target.closest('[data-stop]'))document.querySelector('.sales-modal-backdrop')?.remove()});
document.addEventListener('submit',e=>{if(e.target.id!=='customer-form')return;e.preventDefault();try{const d=new FormData(e.target);Flows.createCustomer({name:d.get('name'),orgNumber:d.get('orgNumber'),email:d.get('email'),phone:d.get('phone'),paymentTermsDays:Number(d.get('paymentTermsDays')),reminderFeeAgreed:d.get('reminderFeeAgreed')==='yes'});customers=Demo.section('customers');document.querySelector('.sales-modal-backdrop')?.remove();message='Kunden sparades och kan nu användas i Kundfakturor.';render()}catch(err){message=err.message;render()}});
if(!isDemo||!Demo||!Flows)app.innerHTML='<main class="boot"><strong>Kundregistret i denna version är en demomodul</strong><span>Öppna GitHub Pages-demon eller lägg till ?demo=1.</span></main>';else{customers=Demo.section('customers');render()}
