const app=document.getElementById('dashboard-app');
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const Demo=globalThis.RollandsDemoScenario;
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ore(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function q(path){return `${path}${isDemo?'?demo=1':''}`}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB<br>${isDemo?'Demoföretag':'Skyddad företagsmiljö'}</div><div class="side-group"><span>Arbetsyta</span><a class="side-link active" href="${q('./dashboard.html')}">Översikt</a></div><div class="sidebar-footer">${isDemo?'Gemensam Demo v1 · fiktiv data':'Personlig session'}</div></aside>`}
function card(title,text,href,badge){return `<a class="module-card ready" href="${q(href)}"><div><span class="module-state">Öppna modul</span><h3>${esc(title)}</h3><p>${esc(text)}</p></div><strong>${esc(String(badge))}</strong></a>`}
function metric(label,value,sub=''){return `<article class="dash-metric"><span>${esc(label)}</span><strong>${value}</strong>${sub?`<small>${esc(sub)}</small>`:''}</article>`}
function metricsFromDemo(){const s=Demo.state(),open=s.customerInvoices.filter(i=>i.remainingOre>0&&i.status!=='Utkast'),overdue=open.filter(i=>i.dueDate<Demo.AS_OF_DATE),payables=s.supplierInvoices.filter(i=>['coded','approved','payment-prepared'].includes(i.status)),pendingInv=s.inventoryAdjustments.filter(a=>a.status==='pending'),openAuto=s.automationProposals.filter(p=>['manual-review','ready-for-approval'].includes(p.status));return{customers:s.customers.length,invoices:s.customerInvoices.length,openCount:open.length,openOre:open.reduce((n,i)=>n+i.remainingOre,0),overdueOre:overdue.reduce((n,i)=>n+i.remainingOre,0),payables:payables.length,bank:s.bankPayments.filter(p=>p.status!=='posted').length,automation:openAuto.length,suppliers:s.supplierPendingChanges.filter(c=>c.status==='pending').length,inventory:pendingInv.length,accounting:s.accountingEntries.length,reports:s.accountingEntries.length,payroll:s.payrollRuns.filter(r=>r.status==='validated').length,documents:s.documents.length}}
async function api(path){const r=await fetch(`/api/v1${path}`,{credentials:'same-origin',headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Begäran misslyckades.');return d}
async function metricsFromApi(){const m={customers:'—',invoices:'—',openCount:0,openOre:0,overdueOre:0,payables:0,bank:0,automation:0,suppliers:0,inventory:0,accounting:0,reports:0,payroll:0,documents:0};try{const inv=(await api('/receivables/invoices')).invoices||[];m.invoices=inv.length;m.openCount=inv.filter(i=>i.remainingOre>0).length;m.openOre=inv.reduce((n,i)=>n+Math.max(0,Number(i.remainingOre||0)),0)}catch{}return m}
function render(m){app.innerHTML=`<div class="dash-shell">${sidebar()}<section class="dash-main"><header class="topbar"><div><h1>Översikt</h1><p>${isDemo?Demo.AS_OF_DATE:new Date().toLocaleDateString('sv-SE')} · företagets arbetsdag</p></div><div class="user-chip"><b>${isDemo?'Demoanvändare':'Inloggad användare'}</b></div></header><main class="content">${isDemo?'<div class="demo-banner"><b>Sammanhängande Demo v1.</b> Alla huvudmoduler använder samma fiktiva scenario. Bankfiler/CAMT är medvetet utelämnat just nu.</div>':''}<section class="dash-hero"><div><span class="eyebrow">Rollands plattform</span><h2>Ett arbetsflöde för hela småföretaget</h2><p>Försäljning, leverantörer, bank, bokföring, rapporter, lager, lön, dokument och webbplats ligger nu i samma portal.</p><p><a class="button" href="${q('./uat.html')}">Starta hela demoguiden</a></p></div><div class="hero-date">${isDemo?Demo.AS_OF_DATE:'Idag'}</div></section><section class="dash-metrics">${metric('Öppet kundsaldo',ore(m.openOre),`${m.openCount} öppna fakturor`)}${metric('Förfallet',ore(m.overdueOre),'kräver uppföljning')}${metric('Leverantörsflöden',m.payables,'kontering/attest/betalning')}${metric('Bokförda verifikationer',m.accounting,'gemensam bokföringsvy')}</section><section class="attention"><div class="section-head"><div><span class="eyebrow">Arbetsyta</span><h2>Alla huvudmoduler</h2></div></div><div class="module-grid">${card('Kunder','Kundregister och betalningsvillkor.','./customers.html',m.customers)}${card('Kundfakturor','Skapa, förhandsvisa och bokför kundfakturor.','./invoices.html',m.invoices)}${card('Kundreskontra','Öppna, förfallna och betalda kundfordringar.','./receivables.html',m.openCount)}${card('Bank & avstämning','Matcha befintliga demoinbetalningar mot kundfordringar.','./bank.html',m.bank)}${card('Leverantörsfakturor','Kontering, attest, skuld och betalningsflöde.','./payables.html',m.payables)}${card('Leverantörer','Masterdata och kontrollerade betalningsuppgifter.','./suppliers.html',m.suppliers)}${card('Lager','Saldo, svinn, inventering och justeringar.','./inventory.html',m.inventory)}${card('Bokföring','Verifikationer, periodlås och rättelser.','./accounting.html',m.accounting)}${card('Rapporter','Balans, huvudbok, resultat och momsunderlag.','./reports.html',m.reports)}${card('Lön','Aggregerad lönejournal och bokföring.','./payroll.html',m.payroll)}${card('Dokument','Originalunderlag, kontrollsumma och affärskoppling.','./documents.html',m.documents)}${card('Automationskö','Regel-/AI-förslag som kräver mänsklig granskning.','./automation.html',m.automation)}${card('Webbplats & innehåll','Hantera publik webb och förhandsvisning.','./website.html','CMS')}</div></section></main></section></div>`}
async function load(){if(isDemo){if(!Demo)throw new Error('Gemensam demodata saknas.');render(metricsFromDemo());return}render(await metricsFromApi())}
load().catch(e=>{app.innerHTML=`<main class="boot"><strong>Översikten kunde inte laddas</strong><span>${esc(e.message)}</span></main>`});
