const app=document.getElementById('invoices-app');
const Demo=globalThis.RollandsDemoScenario,Flows=globalThis.RollandsDemoWorkflows,Money=globalThis.RollandsMoney;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let customers=[],invoices=[],selectedId='',message='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function q(path){return `${path}${isDemo?'?demo=1':''}`}
function money(v){return Money?.formatSek?Money.formatSek(Number(v||0)):new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK'}).format(Number(v||0)/100)}
function selected(){return invoices.find(i=>i.id===selectedId)||invoices[0]||null}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB<br>Demoföretag</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${q('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link" href="${q('./customers.html')}">Kunder</a><a class="side-link active" href="${q('./invoices.html')}">Kundfakturor</a><a class="side-link" href="${q('./index.html')}">Kundreskontra</a></div><div class="sidebar-footer">Utkast bokförs först när ni väljer Bokför & skicka i demon.</div></aside>`}
function status(v){return `<span class="sales-status ${esc(v)}">${esc(v)}</span>`}
function render(){const invoice=selected();const open=invoices.filter(i=>i.remainingOre>0&&i.status!=='Utkast'),drafts=invoices.filter(i=>i.status==='Utkast');app.innerHTML=`<div class="sales-shell">${sidebar()}<section class="sales-main"><header class="topbar"><div><h1>Kundfakturor</h1><p>Försäljning · fakturering · bokföring</p></div><div class="user-chip"><b>Demo Försäljning</b></div></header><main class="sales-content"><div class="demo-banner"><b>Sammanhängande demo.</b> En bokförd faktura hamnar direkt i Kundreskontra och Bokföring. Utskrift kan sparas som PDF via webbläsarens utskriftsdialog.</div>${message?`<div class="notice">${esc(message)}</div>`:''}<section class="sales-summary"><article><span>Fakturor</span><strong>${invoices.length}</strong></article><article><span>Utkast</span><strong>${drafts.length}</strong></article><article><span>Öppet saldo</span><strong>${money(open.reduce((s,i)=>s+i.remainingOre,0))}</strong></article><article><span>Bokförda/betalda</span><strong>${invoices.filter(i=>i.status!=='Utkast').length}</strong></article></section><div class="sales-toolbar"><div class="sales-actions"><a class="button ghost" href="${q('./customers.html')}">Kundregister</a><a class="button ghost" href="${q('./index.html')}">Kundreskontra</a></div><button class="button" data-action="new">Ny kundfaktura</button></div><section class="sales-panel"><div class="sales-head"><div><span class="eyebrow">Fakturor</span><h2>Fakturajournal</h2></div></div><div class="sales-table-wrap"><table class="sales-table"><thead><tr><th>Nr</th><th>Kund</th><th>Datum</th><th>Förfallodatum</th><th>Status</th><th class="money">Total</th><th></th></tr></thead><tbody>${invoices.map(i=>`<tr><td><b>${esc(i.invoiceNumber)}</b><br><small>OCR ${esc(i.ocr)}</small></td><td>${esc(i.customerName)}<br><small>${esc(i.customerNumber)}</small></td><td>${esc(i.invoiceDate)}</td><td>${esc(i.dueDate)}</td><td>${status(i.status)}</td><td class="money">${money(i.totalOre)}</td><td><button class="button ghost small" data-select="${esc(i.id)}">Visa</button></td></tr>`).join('')}</tbody></table></div></section>${invoice?preview(invoice):''}</main></section></div>`}
function preview(i){return `<section class="sales-panel" style="margin-top:18px"><div class="sales-head no-print"><div><span class="eyebrow">Fakturaförhandsvisning</span><h2>${esc(i.invoiceNumber)} · ${esc(i.customerName)}</h2></div><div class="sales-actions">${i.status==='Utkast'?`<button class="button" data-action="post" data-id="${esc(i.id)}">Bokför & skicka demo</button>`:''}<button class="button ghost" data-action="print">Skriv ut / spara PDF</button></div></div><div class="print-source"><article class="invoice-preview"><header><div><strong style="font-size:1.5rem;color:#123c31">Rollands Frukt o Grönt AB</strong><p>Billdal · Org.nr 556406-5059</p></div><div><span class="eyebrow">FAKTURA</span><h2>${esc(i.invoiceNumber)}</h2><p>OCR ${esc(i.ocr)}</p></div></header><div class="two"><div><b>Kund</b><p>${esc(i.customerName)}<br>${esc(i.customerNumber)}</p></div><div><b>Datum</b><p>Fakturadatum ${esc(i.invoiceDate)}<br>Förfallodatum ${esc(i.dueDate)}</p></div></div><table><thead><tr><th>Beskrivning</th><th>Antal</th><th>Á-pris</th><th>Moms</th><th>Belopp</th></tr></thead><tbody>${(i.lines||[]).map(l=>`<tr><td>${esc(l.description)}</td><td>${esc((Number(l.quantityMilli)/1000).toLocaleString('sv-SE',{maximumFractionDigits:3}))}</td><td>${money(l.unitPriceOre)}</td><td>${esc((Number(l.vatBasisPoints)/100).toLocaleString('sv-SE'))} %</td><td>${money(l.netOre)}</td></tr>`).join('')}</tbody></table><div class="totals"><div><span>Netto</span><strong>${money(i.netOre)}</strong></div><div><span>Moms</span><strong>${money(i.vatOre)}</strong></div><div class="grand"><span>Att betala</span><strong>${money(i.totalOre)}</strong></div></div><p><b>Betalning:</b> Bankgiro 123-4567 · ange OCR ${esc(i.ocr)}</p></article></div></section>`}
function newModal(){const customerParam=new URLSearchParams(location.search).get('customer')||'';document.body.insertAdjacentHTML('beforeend',`<div class="sales-modal-backdrop" data-close><section class="sales-modal" data-stop><header><div><span class="eyebrow">Ny kundfaktura</span><h2>Skapa fakturautkast</h2></div><button type="button" data-close>×</button></header><form class="sales-form" id="invoice-form"><label>Kund<select name="customerId" required><option value="">Välj kund</option>${customers.map(c=>`<option value="${esc(c.id)}" ${c.id===customerParam?'selected':''}>${esc(c.customerNumber)} – ${esc(c.name)}</option>`).join('')}</select></label><div class="three"><label>Fakturadatum<input type="date" name="invoiceDate" value="${Demo.AS_OF_DATE}" required></label><label>Förfallodatum<input type="date" name="dueDate" value="2026-10-17" required></label><label>Momssats<select name="vat"><option value="25">25 %</option><option value="12">12 %</option><option value="6">6 %</option><option value="0">0 %</option></select></label></div><label>Beskrivning<input name="description" value="Företagsfrukt september" required></label><div class="two"><label>Antal<input name="quantity" value="1" inputmode="decimal" required></label><label>Pris exkl. moms<input name="price" value="2500,00" inputmode="decimal" required></label></div><div class="notice"><b>Demo:</b> Fakturan sparas först som utkast. Bokföring skapas bara när ni väljer “Bokför & skicka demo”.</div><div class="sales-actions"><button type="button" class="button ghost" data-close>Avbryt</button><button class="button" type="submit">Skapa utkast</button></div></form></section></div>`)}
function refresh(id){customers=Demo.section('customers');invoices=Demo.section('customerInvoices');if(id)selectedId=id;else if(!selectedId)selectedId=invoices[0]?.id||'';render()}
document.addEventListener('click',e=>{const select=e.target.closest('[data-select]');if(select){selectedId=select.dataset.select;render();return}const a=e.target.closest('[data-action]');if(a?.dataset.action==='new'){newModal();return}if(a?.dataset.action==='post'){try{Flows.postCustomerInvoice(a.dataset.id);message='Fakturan bokfördes. Den syns nu i Kundreskontra och Bokföring.';refresh(a.dataset.id)}catch(err){message=err.message;render()}return}if(a?.dataset.action==='print'){window.print();return}if((e.target.matches('[data-close]')||e.target.closest('[data-close]'))&&!e.target.closest('[data-stop]'))document.querySelector('.sales-modal-backdrop')?.remove()});
document.addEventListener('submit',e=>{if(e.target.id!=='invoice-form')return;e.preventDefault();try{const d=new FormData(e.target);const quantityMilli=Money.parseQuantityMilli(String(d.get('quantity')),{allowZero:false});const unitPriceOre=Money.parseOre(String(d.get('price')),{allowNegative:false,allowZero:false});const vatBasisPoints=Money.parseVatBasisPoints(String(d.get('vat')));const created=Flows.createCustomerInvoice({customerId:d.get('customerId'),invoiceDate:d.get('invoiceDate'),dueDate:d.get('dueDate'),description:d.get('description'),quantityMilli,unitPriceOre,vatBasisPoints});document.querySelector('.sales-modal-backdrop')?.remove();message=`Fakturautkast ${created.invoiceNumber} skapades.`;refresh(created.id)}catch(err){message=err.message;render()}});
if(!isDemo||!Demo||!Flows||!Money)app.innerHTML='<main class="boot"><strong>Kundfakturering i denna version är en demomodul</strong><span>Öppna GitHub Pages-demon eller lägg till ?demo=1.</span></main>';else refresh();
