const app=document.getElementById('receivables-app');
const Demo=globalThis.RollandsDemoScenario,Flows=globalThis.RollandsDemoWorkflows;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
let invoices=[],filter='open',message='';
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function money(v){return new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',minimumFractionDigits:2}).format(Number(v||0)/100)}
function q(path){return `${path}${isDemo?'?demo=1':''}`}
function sidebar(){return `<aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB<br>Demoföretag</div><div class="side-group"><span>Arbetsyta</span><a class="side-link" href="${q('./dashboard.html')}">Översikt</a></div><div class="side-group"><span>Försäljning</span><a class="side-link" href="${q('./customers.html')}">Kunder</a><a class="side-link" href="${q('./invoices.html')}">Kundfakturor</a><a class="side-link active" href="${q('./receivables.html')}">Kundreskontra</a></div><div class="sidebar-footer">Gemensam faktura- och betalningsdata i demon.</div></aside>`}
function visible(){if(filter==='all')return invoices;if(filter==='paid')return invoices.filter(i=>i.remainingOre===0);if(filter==='overdue')return invoices.filter(i=>i.remainingOre>0&&i.dueDate<Demo.AS_OF_DATE);return invoices.filter(i=>i.remainingOre>0&&i.status!=='Utkast')}
function status(v){return `<span class="sales-status ${esc(v)}">${esc(v)}</span>`}
function render(){const open=invoices.filter(i=>i.remainingOre>0&&i.status!=='Utkast'),overdue=open.filter(i=>i.dueDate<Demo.AS_OF_DATE),rows=visible();app.innerHTML=`<div class="sales-shell">${sidebar()}<section class="sales-main"><header class="topbar"><div><h1>Kundreskontra</h1><p>Försäljning · öppna kundfordringar</p></div><div class="user-chip"><b>Demo Ekonomi</b></div></header><main class="sales-content"><div class="demo-banner"><b>Gemensamt UAT-scenario.</b> Fakturor som bokförs i Kundfakturor visas här direkt. Bankmatchningar använder samma restbelopp.</div>${message?`<div class="notice">${esc(message)}</div>`:''}<section class="sales-summary"><article><span>Öppet saldo</span><strong>${money(open.reduce((s,i)=>s+i.remainingOre,0))}</strong></article><article><span>Förfallet</span><strong>${money(overdue.reduce((s,i)=>s+i.remainingOre,0))}</strong></article><article><span>Öppna fakturor</span><strong>${open.length}</strong></article><article><span>Betalda</span><strong>${invoices.filter(i=>i.remainingOre===0).length}</strong></article></section><div class="sales-toolbar"><div class="sales-actions"><button class="button ghost ${filter==='open'?'active':''}" data-filter="open">Öppna</button><button class="button ghost ${filter==='overdue'?'active':''}" data-filter="overdue">Förfallna</button><button class="button ghost ${filter==='paid'?'active':''}" data-filter="paid">Betalda</button><button class="button ghost ${filter==='all'?'active':''}" data-filter="all">Alla</button></div><div class="sales-actions"><a class="button ghost" href="${q('./invoices.html')}">Kundfakturor</a><a class="button" href="${q('./bank.html')}">Bank & avstämning</a></div></div><section class="sales-panel"><div class="sales-table-wrap"><table class="sales-table"><thead><tr><th>Kund</th><th>Faktura</th><th>Förfallodatum</th><th>Status</th><th class="money">Fakturabelopp</th><th class="money">Restbelopp</th><th>Kommentar</th></tr></thead><tbody>${rows.map(i=>`<tr><td><b>${esc(i.customerName)}</b><br><small>${esc(i.customerNumber)}</small></td><td><b>${esc(i.invoiceNumber)}</b><br><small>OCR ${esc(i.ocr)}</small></td><td class="${i.remainingOre>0&&i.dueDate<Demo.AS_OF_DATE?'overdue':''}">${esc(i.dueDate)}</td><td>${status(i.status)}</td><td class="money">${money(i.totalOre)}</td><td class="money"><b>${money(i.remainingOre)}</b></td><td>${(i.comments||[]).length?`${esc(i.comments.at(-1).text)}<br><small>${esc(i.comments.at(-1).authorName)}</small>`:'—'}<br><button class="button ghost small" data-comment="${esc(i.id)}">Lägg kommentar</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty-note">Inga poster i urvalet.</td></tr>'}</tbody></table></div></section></main></section></div>`}
function refresh(){invoices=Demo.section('customerInvoices');render()}
document.addEventListener('click',e=>{const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;render();return}const c=e.target.closest('[data-comment]');if(c){const text=prompt('Intern kommentar på fakturan:');if(!text)return;Demo.patch(state=>{const invoice=state.customerInvoices.find(i=>i.id===c.dataset.comment);if(invoice){invoice.comments=invoice.comments||[];invoice.comments.push({id:`comment-${Date.now()}`,text:String(text).slice(0,2000),authorName:'Demo Ekonomi',createdAt:new Date().toISOString()});invoice.commentCount=invoice.comments.length}});message='Kommentaren sparades i det gemensamma demoscenariot.';refresh()}});
if(!isDemo||!Demo||!Flows)app.innerHTML='<main class="boot"><strong>Kundreskontran i denna version är en demomodul</strong><span>Öppna GitHub Pages-demon eller lägg till ?demo=1.</span></main>';else refresh();
