const app=document.getElementById('uat-app');
const Demo=globalThis.RollandsDemoScenario;
const isDemo=location.hostname.endsWith('github.io')||new URLSearchParams(location.search).has('demo');
const KEY='rollands-uat-checklist-v2',q='?demo=1';
const steps=[
{id:'public',title:'1. Publik webb → företagsportal',text:'Öppna den publika Rollands-sidan och kontrollera att Demoportal leder till samma privata arbetsyta och att den publika sidan inte visar intern ekonomi.',href:'../'},
{id:'customer',title:'2. Kunder – skapa en ny demokund',text:'Öppna Kunder, skapa en fiktiv företagskund och kontrollera att den direkt blir valbar i Kundfakturor.',href:`./customers.html${q}`},
{id:'invoice',title:'3. Kundfakturor – skapa och bokför',text:'Skapa ett fakturautkast med antal, pris och moms. Förhandsvisa fakturan och välj Bokför & skicka demo. Fakturan ska få en verifikation och gå från Utkast till Bokförd.',href:`./invoices.html${q}`},
{id:'receivables',title:'4. Kundreskontra – följ den bokförda fakturan',text:'Kontrollera att den nya fakturan syns med samma kund, fakturanummer, total- och restbelopp. Lägg gärna en intern kommentar.',href:`./receivables.html${q}`},
{id:'bank',title:'5. Bank – analysera en befintlig demoinbetalning',text:'Ingen CAMT/BAM-import används i denna version. Analysera den redan registrerade inbetalningen med referens 310002 och 3 925,00 kr.',href:`./bank.html${q}`},
{id:'automation-bank',title:'6. Automationskö – godkänn kundinbetalningen',text:'Förslaget ska visa Debet 1930 och Kredit 1510. När det godkänns i demon ska faktura 310002 bli Betald, bankhändelsen bokförd och en ny verifikation skapas.',href:`./automation.html${q}`},
{id:'automation-supplier',title:'7. Automation – granska leverantörskontering',text:'Granska Kustens Emballage AB / KE-2088. Konton kan ändras före godkännande; godkännandet ska uppdatera samma leverantörsfaktura.',href:`./automation.html${q}`},
{id:'payables',title:'8. Leverantörsfakturor – attest till betalning',text:'Följ BKS-771 genom skuldbokföring, betalningsförberedelse, separat frisläppning och bankbekräftelse. Pengar skickas inte till verklig bank.',href:`./payables.html${q}`},
{id:'suppliers',title:'9. Leverantörer – fyrögonprincip',text:'Kontrollera att ändring av betalningsuppgifter ligger i separat godkännandekö innan aktiv masterdata ändras.',href:`./suppliers.html${q}`},
{id:'inventory',title:'10. Lager – svinn och inventering',text:'Registrera en lagerrörelse och skapa en inventeringsdifferens. Godkänn den och kontrollera att saldot uppdateras.',href:`./inventory.html${q}`},
{id:'payroll',title:'11. Lön – journal till bokföring',text:'Importera eller använd den aggregerade lönejournalen och bokför den. Kontrollera därefter att verifikationen syns i Bokföring.',href:`./payroll.html${q}`},
{id:'documents',title:'12. Dokument – spårbarhet',text:'Kontrollera att dokument har kategori, SHA-256-exempel och koppling till samma affärs-id som leverantörsfakturorna.',href:`./documents.html${q}`},
{id:'accounting',title:'13. Bokföring – kontrollera hela kedjan',text:'Verifiera kundfakturor, kundbetalningar, leverantörsflöden och bokförd lönejournal. Original rättas med motverifikation och periodlås ska vara tydligt.',href:`./accounting.html${q}`},
{id:'reports',title:'14. Rapporter – kontrollera att siffrorna följer bokföringen',text:'Balanslista och huvudbok ska räknas från samma verifikationer. Momsavstämningen ska läsa samma kund- och leverantörsfakturor.',href:`./reports.html${q}`},
{id:'cms',title:'15. Webbplats & innehåll',text:'Ändra en ofarlig demotext, spara utkast och förhandsvisa. Juridiskt namn och organisationsnummer ska hållas separerade från redigerbart marknadsinnehåll.',href:`./website.html${q}`},
{id:'overall',title:'16. Helhetsbedömning',text:'Gå tillbaka till Översikt. Kontrollera att det känns som ett enda småföretagssystem utan döda huvudlänkar eller separata demovärldar.',href:`./dashboard.html${q}`}
];
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function loadState(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}}function saveState(v){localStorage.setItem(KEY,JSON.stringify(v))}function label(v){return({ok:'Godkänd',issue:'Fel / behöver rättas',change:'Önskad ändring',untested:'Ej testad'})[v]||'Ej testad'}
function render(){const state=loadState(),done=steps.filter(s=>state[s.id]?.status==='ok').length;app.innerHTML=`<div class="uat-shell"><aside class="sidebar"><div class="logo"><strong>Rollands</strong><small>FÖRETAGSPORTAL</small></div><div class="company-pill">Rollands Frukt o Grönt AB<br>UAT / Demo v1</div><div class="side-group"><span>Test</span><a class="side-link active" href="./uat.html${q}">Testa systemet</a><a class="side-link" href="./dashboard.html${q}">Översikt</a></div><div class="sidebar-footer">All data är fiktiv. CAMT/bankfilimport ingår inte i denna testomgång.</div></aside><section class="uat-main"><header class="topbar"><div><h1>Testa hela Demo v1</h1><p>Scenario ${esc(Demo?.VERSION||'saknas')}</p></div><button class="button ghost" data-action="reset-demo">Återställ demoscenario</button></header><main class="content"><div class="demo-banner"><b>Målet:</b> gå från publik webb till försäljning, ekonomi, lager, lön, dokument och rapporter i ett sammanhängande scenario.</div><section class="uat-summary"><article><span>Godkända steg</span><strong>${done}/${steps.length}</strong></article><article><span>Scenario-datum</span><strong>${esc(Demo?.AS_OF_DATE||'—')}</strong></article><article><span>Datakälla</span><strong>Gemensam Demo v1</strong></article></section><section class="uat-list">${steps.map(step=>{const row=state[step.id]||{status:'untested',note:''};return `<article class="uat-step ${esc(row.status)}"><div class="uat-step-head"><div><span class="step-status">${esc(label(row.status))}</span><h2>${esc(step.title)}</h2></div><a class="button" href="${esc(step.href)}">Öppna modul</a></div><p>${esc(step.text)}</p><div class="uat-controls"><select data-status="${esc(step.id)}"><option value="untested" ${row.status==='untested'?'selected':''}>Ej testad</option><option value="ok" ${row.status==='ok'?'selected':''}>Godkänd</option><option value="issue" ${row.status==='issue'?'selected':''}>Fel / behöver rättas</option><option value="change" ${row.status==='change'?'selected':''}>Önskad ändring</option></select><textarea data-note="${esc(step.id)}" rows="2" placeholder="Anteckning…">${esc(row.note||'')}</textarea></div></article>`}).join('')}</section></main></section></div>`}
document.addEventListener('change',e=>{const id=e.target.dataset.status;if(!id)return;const s=loadState();s[id]={...(s[id]||{}),status:e.target.value,note:document.querySelector(`[data-note="${CSS.escape(id)}"]`)?.value||''};saveState(s);render()});document.addEventListener('input',e=>{const id=e.target.dataset.note;if(!id)return;const s=loadState();s[id]={...(s[id]||{status:'untested'}),note:e.target.value};saveState(s)});document.addEventListener('click',e=>{if(!e.target.closest('[data-action="reset-demo"]'))return;if(!confirm('Återställa hela Demo v1 och UAT-markeringarna?'))return;Demo?.reset();localStorage.removeItem(KEY);render()});
if(!isDemo)app.innerHTML='<main class="boot"><strong>UAT-guiden är avsedd för demon</strong><span>Öppna sidan med ?demo=1.</span></main>';else if(!Demo)app.innerHTML='<main class="boot"><strong>Demoscenario saknas</strong><span>Gemensam demodata kunde inte laddas.</span></main>';else render();
